-- Corvis enterprise core v1
-- Snowflake is the structured system of record; source bytes remain in private immutable object storage.

CREATE SCHEMA IF NOT EXISTS PM_CONTROL;
CREATE SCHEMA IF NOT EXISTS PM_SOURCE;
CREATE SCHEMA IF NOT EXISTS PM_IDENTITY;
CREATE SCHEMA IF NOT EXISTS PM_FACTS;
CREATE SCHEMA IF NOT EXISTS PM_CONSOLIDATED;
CREATE SCHEMA IF NOT EXISTS PM_SEMANTIC;
CREATE SCHEMA IF NOT EXISTS PM_SERVING;

CREATE TABLE IF NOT EXISTS PM_CONTROL.TENANT_ROLE_GRANT (
  TENANT_ID STRING NOT NULL,
  ROLE_NAME STRING NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (TENANT_ID, ROLE_NAME)
);

CREATE OR REPLACE ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION AS (ROW_TENANT_ID STRING)
RETURNS BOOLEAN ->
  EXISTS (
    SELECT 1 FROM PM_CONTROL.TENANT_ROLE_GRANT G
    WHERE G.TENANT_ID = ROW_TENANT_ID AND UPPER(G.ROLE_NAME) = UPPER(CURRENT_ROLE())
  );

CREATE TABLE IF NOT EXISTS PM_SOURCE.DOCUMENT (
  TENANT_ID STRING NOT NULL,
  DOCUMENT_ID STRING NOT NULL,
  DOCUMENT_FAMILY_ID STRING,
  DISPLAY_NAME STRING NOT NULL,
  MEDIA_TYPE STRING NOT NULL,
  STATUS STRING NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  CREATED_BY STRING NOT NULL,
  PRIMARY KEY (TENANT_ID, DOCUMENT_ID)
);
ALTER TABLE PM_SOURCE.DOCUMENT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_SOURCE.DOCUMENT_ARTIFACT_VERSION (
  TENANT_ID STRING NOT NULL,
  DOCUMENT_ARTIFACT_VERSION_ID STRING NOT NULL,
  DOCUMENT_ID STRING NOT NULL,
  INGESTION_ID STRING NOT NULL,
  OBJECT_URI STRING NOT NULL,
  SIZE_BYTES NUMBER NOT NULL,
  SHA256 STRING,
  STORAGE_VERSION STRING,
  MALWARE_SCAN_STATUS STRING NOT NULL DEFAULT 'pending',
  QUARANTINE_STATUS STRING NOT NULL DEFAULT 'pending',
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, DOCUMENT_ARTIFACT_VERSION_ID)
);
ALTER TABLE PM_SOURCE.DOCUMENT_ARTIFACT_VERSION ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_SOURCE.SOURCE_REFERENCE (
  TENANT_ID STRING NOT NULL,
  SOURCE_REFERENCE_ID STRING NOT NULL,
  DOCUMENT_ID STRING NOT NULL,
  DOCUMENT_ARTIFACT_VERSION_ID STRING NOT NULL,
  PAGE_NUMBER NUMBER,
  SHEET_NAME STRING,
  CELL_RANGE STRING,
  BBOX VARIANT,
  EXCERPT STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, SOURCE_REFERENCE_ID)
);
ALTER TABLE PM_SOURCE.SOURCE_REFERENCE ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_SOURCE.DOCUMENT_CHUNK (
  TENANT_ID STRING NOT NULL,
  CHUNK_ID STRING NOT NULL,
  DOCUMENT_ID STRING NOT NULL,
  SOURCE_REFERENCE_ID STRING NOT NULL,
  CHUNK_ORDINAL NUMBER NOT NULL,
  TEXT STRING NOT NULL,
  METADATA VARIANT,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, CHUNK_ID)
);
ALTER TABLE PM_SOURCE.DOCUMENT_CHUNK ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_IDENTITY.FUND (
  GLOBAL_FUND_ID STRING NOT NULL PRIMARY KEY,
  CANONICAL_NAME STRING NOT NULL,
  MANAGER_NAME STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PM_IDENTITY.COMPANY (
  GLOBAL_COMPANY_ID STRING NOT NULL PRIMARY KEY,
  CANONICAL_NAME STRING NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PM_FACTS.OBSERVATION (
  TENANT_ID STRING NOT NULL,
  OBSERVATION_ID STRING NOT NULL,
  FUND_ID STRING NOT NULL,
  COMPANY_ID STRING,
  HOLDING_ID STRING,
  INSTRUMENT_ID STRING,
  METRIC_CODE STRING NOT NULL,
  VALUE_NUMBER NUMBER(38,10),
  VALUE_STRING STRING,
  CURRENCY STRING,
  ECONOMIC_PERIOD STRING,
  REPORT_DATE DATE,
  ACTUALITY STRING,
  REVIEW_STATE STRING NOT NULL,
  VERSION NUMBER NOT NULL DEFAULT 1,
  SOURCE_REFERENCE_ID STRING NOT NULL,
  EXTRACTION_RUN_ID STRING,
  SCHEMA_VERSION STRING NOT NULL,
  SKILL_VERSION STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  UPDATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, OBSERVATION_ID)
);
ALTER TABLE PM_FACTS.OBSERVATION ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_FACTS.REVIEW_EVENT (
  TENANT_ID STRING NOT NULL,
  REVIEW_EVENT_ID STRING NOT NULL,
  OBSERVATION_ID STRING NOT NULL,
  ACTOR_SUBJECT STRING NOT NULL,
  DECISION STRING NOT NULL,
  REASON_CODE STRING NOT NULL,
  BEFORE_VALUE VARIANT,
  AFTER_VALUE VARIANT,
  OBSERVATION_VERSION NUMBER NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, REVIEW_EVENT_ID)
);
ALTER TABLE PM_FACTS.REVIEW_EVENT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONSOLIDATED.CONSOLIDATED_FACT (
  TENANT_ID STRING NOT NULL,
  CONSOLIDATED_FACT_ID STRING NOT NULL,
  FUND_ID STRING NOT NULL,
  SUBJECT_TYPE STRING NOT NULL,
  SUBJECT_ID STRING NOT NULL,
  METRIC_CODE STRING NOT NULL,
  ECONOMIC_PERIOD STRING,
  VALUE VARIANT NOT NULL,
  SOURCE_OBSERVATION_IDS ARRAY NOT NULL,
  CONSOLIDATION_RULE_VERSION STRING NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, CONSOLIDATED_FACT_ID)
);
ALTER TABLE PM_CONSOLIDATED.CONSOLIDATED_FACT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONSOLIDATED.FUND_PERIOD_SNAPSHOT (
  TENANT_ID STRING NOT NULL,
  SNAPSHOT_ID STRING NOT NULL,
  FUND_ID STRING NOT NULL,
  REPORT_PERIOD STRING NOT NULL,
  VERSION NUMBER NOT NULL,
  STATUS STRING NOT NULL,
  FACT_IDS ARRAY NOT NULL,
  BLOCKING_EXCEPTION_COUNT NUMBER NOT NULL DEFAULT 0,
  SCHEMA_VERSION STRING NOT NULL,
  TAXONOMY_VERSION STRING NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  PUBLISHED_AT TIMESTAMP_TZ,
  PRIMARY KEY (TENANT_ID, SNAPSHOT_ID, VERSION)
);
ALTER TABLE PM_CONSOLIDATED.FUND_PERIOD_SNAPSHOT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_SEMANTIC.METRIC_DEFINITION (
  METRIC_CODE STRING NOT NULL PRIMARY KEY,
  DISPLAY_NAME STRING NOT NULL,
  DATA_TYPE STRING NOT NULL,
  AGGREGATION_BEHAVIOR STRING NOT NULL,
  UNIT_TYPE STRING,
  FX_BEHAVIOR STRING,
  COMPATIBILITY_RULE VARIANT,
  DEFINITION_VERSION STRING NOT NULL,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE OR REPLACE SECURE VIEW PM_SERVING.OBSERVATIONS AS
SELECT TENANT_ID, OBSERVATION_ID, FUND_ID, COMPANY_ID, HOLDING_ID, INSTRUMENT_ID, METRIC_CODE,
       VALUE_NUMBER, VALUE_STRING, CURRENCY, ECONOMIC_PERIOD, REPORT_DATE, REVIEW_STATE,
       SOURCE_REFERENCE_ID, VERSION, UPDATED_AT
FROM PM_FACTS.OBSERVATION
WHERE REVIEW_STATE IN ('approved','review_required');

CREATE OR REPLACE SECURE VIEW PM_SERVING.FUND_PERIOD_SNAPSHOTS AS
SELECT TENANT_ID, SNAPSHOT_ID, FUND_ID, REPORT_PERIOD, VERSION, STATUS, FACT_IDS,
       BLOCKING_EXCEPTION_COUNT, SCHEMA_VERSION, TAXONOMY_VERSION, CREATED_AT, PUBLISHED_AT
FROM PM_CONSOLIDATED.FUND_PERIOD_SNAPSHOT;

CREATE TABLE IF NOT EXISTS PM_CONTROL.AUDIT_EVENT (
  TENANT_ID STRING NOT NULL,
  AUDIT_EVENT_ID STRING NOT NULL,
  OCCURRED_AT TIMESTAMP_TZ NOT NULL,
  WORKSPACE_ID STRING NOT NULL,
  ACTOR_SUBJECT STRING NOT NULL,
  SESSION_ID STRING NOT NULL,
  ACTION STRING NOT NULL,
  TARGET_TYPE STRING NOT NULL,
  TARGET_ID STRING,
  OUTCOME STRING NOT NULL,
  CORRELATION_ID STRING NOT NULL,
  METADATA VARIANT,
  PRIMARY KEY (TENANT_ID, AUDIT_EVENT_ID)
);
ALTER TABLE PM_CONTROL.AUDIT_EVENT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);
