-- Corvis governance and delivery controls v1

CREATE TABLE IF NOT EXISTS PM_CONTROL.ENTITLEMENT_GRANT (
  TENANT_ID STRING NOT NULL,
  GRANT_ID STRING NOT NULL,
  SUBJECT_ID STRING NOT NULL,
  SUBJECT_TYPE STRING NOT NULL,
  RESOURCE_TYPE STRING NOT NULL,
  RESOURCE_ID STRING,
  PERMISSION STRING NOT NULL,
  EFFECTIVE_FROM TIMESTAMP_TZ NOT NULL,
  EFFECTIVE_TO TIMESTAMP_TZ,
  CREATED_BY STRING NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, GRANT_ID)
);
ALTER TABLE PM_CONTROL.ENTITLEMENT_GRANT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.DATA_RIGHTS (
  TENANT_ID STRING NOT NULL,
  RIGHTS_ID STRING NOT NULL,
  RESOURCE_TYPE STRING NOT NULL,
  RESOURCE_ID STRING NOT NULL,
  CLIENT_VISIBLE BOOLEAN NOT NULL DEFAULT TRUE,
  INTERNAL_ANALYTICS_ALLOWED BOOLEAN NOT NULL DEFAULT FALSE,
  MODEL_TRAINING_ALLOWED BOOLEAN NOT NULL DEFAULT FALSE,
  REDISTRIBUTION_ALLOWED BOOLEAN NOT NULL DEFAULT FALSE,
  SOURCE_DOCUMENT_ACCESS_ALLOWED BOOLEAN NOT NULL DEFAULT FALSE,
  EFFECTIVE_FROM TIMESTAMP_TZ NOT NULL,
  EFFECTIVE_TO TIMESTAMP_TZ,
  CONTRACT_REFERENCE STRING,
  PRIMARY KEY (TENANT_ID, RIGHTS_ID)
);
ALTER TABLE PM_CONTROL.DATA_RIGHTS ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.RETENTION_POLICY (
  TENANT_ID STRING NOT NULL,
  DATA_CLASS STRING NOT NULL,
  RETENTION_DAYS NUMBER,
  LEGAL_HOLD BOOLEAN NOT NULL DEFAULT FALSE,
  DELETE_ON_TERMINATION BOOLEAN NOT NULL DEFAULT FALSE,
  POLICY_VERSION STRING NOT NULL,
  EFFECTIVE_FROM TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, DATA_CLASS, POLICY_VERSION)
);
ALTER TABLE PM_CONTROL.RETENTION_POLICY ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.DELETION_REQUEST (
  TENANT_ID STRING NOT NULL,
  DELETION_REQUEST_ID STRING NOT NULL,
  REQUESTED_BY STRING NOT NULL,
  SCOPE VARIANT NOT NULL,
  REASON STRING NOT NULL,
  STATE STRING NOT NULL,
  REQUESTED_AT TIMESTAMP_TZ NOT NULL,
  APPROVED_BY STRING,
  APPROVED_AT TIMESTAMP_TZ,
  COMPLETED_AT TIMESTAMP_TZ,
  COMPLETION_EVIDENCE VARIANT,
  PRIMARY KEY (TENANT_ID, DELETION_REQUEST_ID)
);
ALTER TABLE PM_CONTROL.DELETION_REQUEST ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.PROCESSING_JOB (
  TENANT_ID STRING NOT NULL,
  JOB_ID STRING NOT NULL,
  DOCUMENT_ID STRING NOT NULL,
  STAGE STRING NOT NULL,
  STATE STRING NOT NULL,
  ATTEMPT NUMBER NOT NULL,
  MAX_ATTEMPTS NUMBER NOT NULL,
  CORRELATION_ID STRING NOT NULL,
  VERSION NUMBER NOT NULL,
  LAST_ERROR STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  UPDATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, JOB_ID)
);
ALTER TABLE PM_CONTROL.PROCESSING_JOB ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.OUTBOX_EVENT (
  TENANT_ID STRING NOT NULL,
  EVENT_ID STRING NOT NULL,
  EVENT_TYPE STRING NOT NULL,
  AGGREGATE_TYPE STRING NOT NULL,
  AGGREGATE_ID STRING NOT NULL,
  PAYLOAD VARIANT NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  PUBLISHED_AT TIMESTAMP_TZ,
  ATTEMPT_COUNT NUMBER NOT NULL DEFAULT 0,
  LAST_ERROR STRING,
  PRIMARY KEY (TENANT_ID, EVENT_ID)
);
ALTER TABLE PM_CONTROL.OUTBOX_EVENT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.WEBHOOK_SUBSCRIPTION (
  TENANT_ID STRING NOT NULL,
  WEBHOOK_ID STRING NOT NULL,
  ENDPOINT_URL STRING NOT NULL,
  SECRET_REFERENCE STRING NOT NULL,
  EVENT_TYPES ARRAY NOT NULL,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, WEBHOOK_ID)
);
ALTER TABLE PM_CONTROL.WEBHOOK_SUBSCRIPTION ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.WEBHOOK_DELIVERY (
  TENANT_ID STRING NOT NULL,
  DELIVERY_ID STRING NOT NULL,
  WEBHOOK_ID STRING NOT NULL,
  EVENT_ID STRING NOT NULL,
  ATTEMPT NUMBER NOT NULL,
  STATUS_CODE NUMBER,
  STATE STRING NOT NULL,
  NEXT_ATTEMPT_AT TIMESTAMP_TZ,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  COMPLETED_AT TIMESTAMP_TZ,
  PRIMARY KEY (TENANT_ID, DELIVERY_ID)
);
ALTER TABLE PM_CONTROL.WEBHOOK_DELIVERY ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_SERVING.EXPORT_JOB (
  TENANT_ID STRING NOT NULL,
  EXPORT_ID STRING NOT NULL,
  REQUESTED_BY STRING NOT NULL,
  FORMAT STRING NOT NULL,
  SNAPSHOT_IDS ARRAY,
  STATE STRING NOT NULL,
  OBJECT_URI STRING,
  EXPIRES_AT TIMESTAMP_TZ,
  CHECKSUM_SHA256 STRING,
  MANIFEST VARIANT,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  COMPLETED_AT TIMESTAMP_TZ,
  PRIMARY KEY (TENANT_ID, EXPORT_ID)
);
ALTER TABLE PM_SERVING.EXPORT_JOB ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);
