-- Corvis serving, review and retrieval completion v1
-- Adds missing canonical holdings/instruments, durable document representations and customer-facing read models.

ALTER TABLE PM_SOURCE.DOCUMENT ADD COLUMN IF NOT EXISTS FUND_NAME STRING;
ALTER TABLE PM_SOURCE.DOCUMENT ADD COLUMN IF NOT EXISTS REPORT_PERIOD STRING;
ALTER TABLE PM_SOURCE.DOCUMENT ADD COLUMN IF NOT EXISTS DOCUMENT_TYPE STRING;
ALTER TABLE PM_SOURCE.DOCUMENT ADD COLUMN IF NOT EXISTS PAGE_COUNT NUMBER;
ALTER TABLE PM_SOURCE.DOCUMENT ADD COLUMN IF NOT EXISTS QUALITY STRING;

CREATE TABLE IF NOT EXISTS PM_SOURCE.DOCUMENT_CLASSIFICATION_EVENT (
  TENANT_ID STRING NOT NULL,
  CLASSIFICATION_EVENT_ID STRING NOT NULL,
  DOCUMENT_ID STRING NOT NULL,
  CLASSIFICATION_TYPE STRING NOT NULL,
  CLASSIFICATION_VALUE STRING NOT NULL,
  CONFIDENCE FLOAT,
  METHOD STRING NOT NULL,
  MODEL_VERSION STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, CLASSIFICATION_EVENT_ID)
);
ALTER TABLE PM_SOURCE.DOCUMENT_CLASSIFICATION_EVENT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_SOURCE.DOCUMENT_REPRESENTATION (
  TENANT_ID STRING NOT NULL,
  REPRESENTATION_ID STRING NOT NULL,
  DOCUMENT_ID STRING NOT NULL,
  DOCUMENT_ARTIFACT_VERSION_ID STRING NOT NULL,
  REPRESENTATION_TYPE STRING NOT NULL,
  OBJECT_URI STRING NOT NULL,
  CONTENT_SHA256 STRING,
  PRODUCER STRING NOT NULL,
  PRODUCER_VERSION STRING,
  STATUS STRING NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, REPRESENTATION_ID)
);
ALTER TABLE PM_SOURCE.DOCUMENT_REPRESENTATION ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_FACTS.HOLDING (
  TENANT_ID STRING NOT NULL,
  HOLDING_ID STRING NOT NULL,
  FUND_ID STRING NOT NULL,
  TARGET_TYPE STRING NOT NULL,
  TARGET_COMPANY_ID STRING,
  TARGET_FUND_ID STRING,
  STATUS STRING,
  INVESTMENT_DATE DATE,
  STRATEGY STRING,
  GEOGRAPHY STRING,
  SOURCE_REFERENCE_ID STRING,
  VERSION NUMBER NOT NULL DEFAULT 1,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  UPDATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, HOLDING_ID)
);
ALTER TABLE PM_FACTS.HOLDING ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_FACTS.INSTRUMENT (
  TENANT_ID STRING NOT NULL,
  INSTRUMENT_ID STRING NOT NULL,
  HOLDING_ID STRING NOT NULL,
  INSTRUMENT_TYPE STRING NOT NULL,
  SECURITY_NAME STRING,
  CURRENCY STRING,
  SENIORITY STRING,
  MATURITY_DATE DATE,
  COUPON_RATE NUMBER(18,8),
  SOURCE_REFERENCE_ID STRING,
  VERSION NUMBER NOT NULL DEFAULT 1,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  UPDATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, INSTRUMENT_ID)
);
ALTER TABLE PM_FACTS.INSTRUMENT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

ALTER TABLE PM_FACTS.OBSERVATION ADD COLUMN IF NOT EXISTS CONFIDENCE_SCORE FLOAT;
ALTER TABLE PM_FACTS.OBSERVATION ADD COLUMN IF NOT EXISTS DELTA_DISPLAY STRING;
ALTER TABLE PM_FACTS.OBSERVATION ADD COLUMN IF NOT EXISTS RISK_TIER STRING DEFAULT 'normal';

CREATE TABLE IF NOT EXISTS PM_CONTROL.EXCEPTION (
  TENANT_ID STRING NOT NULL,
  EXCEPTION_ID STRING NOT NULL,
  SNAPSHOT_ID STRING,
  DOCUMENT_ID STRING,
  OBSERVATION_ID STRING,
  CODE STRING NOT NULL,
  SEVERITY STRING NOT NULL,
  STATE STRING NOT NULL,
  DETAIL STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  RESOLVED_AT TIMESTAMP_TZ,
  RESOLVED_BY STRING,
  PRIMARY KEY (TENANT_ID, EXCEPTION_ID)
);
ALTER TABLE PM_CONTROL.EXCEPTION ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONSOLIDATED.RECONCILIATION (
  TENANT_ID STRING NOT NULL,
  RECONCILIATION_ID STRING NOT NULL,
  FUND_ID STRING NOT NULL,
  SUBJECT_TYPE STRING NOT NULL,
  SUBJECT_ID STRING NOT NULL,
  METRIC_CODE STRING NOT NULL,
  ECONOMIC_PERIOD STRING,
  SOURCE_OBSERVATION_IDS ARRAY NOT NULL,
  STATUS STRING NOT NULL,
  RESOLUTION_RULE STRING,
  RESOLVED_OBSERVATION_ID STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  UPDATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, RECONCILIATION_ID)
);
ALTER TABLE PM_CONSOLIDATED.RECONCILIATION ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.CONTROL_EVIDENCE (
  TENANT_ID STRING NOT NULL,
  EVIDENCE_ID STRING NOT NULL,
  CONTROL_CODE STRING NOT NULL,
  EVIDENCE_TYPE STRING NOT NULL,
  EVIDENCE_URI STRING,
  EVIDENCE_PAYLOAD VARIANT,
  PERIOD_START TIMESTAMP_TZ,
  PERIOD_END TIMESTAMP_TZ,
  RESULT STRING NOT NULL,
  GENERATED_AT TIMESTAMP_TZ NOT NULL,
  GENERATED_BY STRING NOT NULL,
  PRIMARY KEY (TENANT_ID, EVIDENCE_ID)
);
ALTER TABLE PM_CONTROL.CONTROL_EVIDENCE ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.FEATURE_FLAG (
  TENANT_ID STRING NOT NULL,
  FLAG_KEY STRING NOT NULL,
  ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
  CONFIG VARIANT,
  UPDATED_AT TIMESTAMP_TZ NOT NULL,
  UPDATED_BY STRING NOT NULL,
  PRIMARY KEY (TENANT_ID, FLAG_KEY)
);
ALTER TABLE PM_CONTROL.FEATURE_FLAG ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.SEMANTIC_QUERY_LOG (
  TENANT_ID STRING NOT NULL,
  SEMANTIC_QUERY_ID STRING NOT NULL,
  ACTOR_SUBJECT STRING NOT NULL,
  QUESTION_HASH STRING NOT NULL,
  RESULT_FACT_IDS ARRAY,
  RESULT_ROW_COUNT NUMBER NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (TENANT_ID, SEMANTIC_QUERY_ID)
);
ALTER TABLE PM_CONTROL.SEMANTIC_QUERY_LOG ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE OR REPLACE SECURE VIEW PM_SERVING.DOCUMENTS AS
WITH ARTIFACT AS (
  SELECT TENANT_ID, DOCUMENT_ID, SIZE_BYTES, MALWARE_SCAN_STATUS, QUARANTINE_STATUS,
         ROW_NUMBER() OVER (PARTITION BY TENANT_ID, DOCUMENT_ID ORDER BY CREATED_AT DESC) AS RN
  FROM PM_SOURCE.DOCUMENT_ARTIFACT_VERSION
), JOB AS (
  SELECT TENANT_ID, DOCUMENT_ID, STAGE, STATE, UPDATED_AT,
         ROW_NUMBER() OVER (PARTITION BY TENANT_ID, DOCUMENT_ID ORDER BY UPDATED_AT DESC) AS RN
  FROM PM_CONTROL.PROCESSING_JOB
), DOC_OBS AS (
  SELECT O.TENANT_ID, R.DOCUMENT_ID, COUNT(*) AS OBSERVATION_COUNT
  FROM PM_FACTS.OBSERVATION O
  JOIN PM_SOURCE.SOURCE_REFERENCE R
    ON R.TENANT_ID = O.TENANT_ID AND R.SOURCE_REFERENCE_ID = O.SOURCE_REFERENCE_ID
  GROUP BY O.TENANT_ID, R.DOCUMENT_ID
)
SELECT D.TENANT_ID,
       D.DOCUMENT_ID,
       D.DISPLAY_NAME,
       D.FUND_NAME,
       D.REPORT_PERIOD,
       COALESCE(D.DOCUMENT_TYPE, D.MEDIA_TYPE) AS DOCUMENT_TYPE,
       D.PAGE_COUNT,
       A.SIZE_BYTES,
       D.STATUS,
       D.QUALITY,
       COALESCE(DO.OBSERVATION_COUNT, 0) AS OBSERVATION_COUNT,
       J.STAGE AS PROCESSING_STAGE,
       J.STATE AS PROCESSING_STATE,
       J.UPDATED_AT AS PROCESSING_UPDATED_AT,
       A.MALWARE_SCAN_STATUS,
       A.QUARANTINE_STATUS,
       D.CREATED_AT
FROM PM_SOURCE.DOCUMENT D
LEFT JOIN ARTIFACT A ON A.TENANT_ID=D.TENANT_ID AND A.DOCUMENT_ID=D.DOCUMENT_ID AND A.RN=1
LEFT JOIN JOB J ON J.TENANT_ID=D.TENANT_ID AND J.DOCUMENT_ID=D.DOCUMENT_ID AND J.RN=1
LEFT JOIN DOC_OBS DO ON DO.TENANT_ID=D.TENANT_ID AND DO.DOCUMENT_ID=D.DOCUMENT_ID;

CREATE OR REPLACE SECURE VIEW PM_SERVING.HOLDINGS AS
SELECT H.TENANT_ID, H.HOLDING_ID, H.FUND_ID, H.TARGET_TYPE, H.TARGET_COMPANY_ID, H.TARGET_FUND_ID,
       H.STATUS, H.INVESTMENT_DATE, H.STRATEGY, H.GEOGRAPHY, H.SOURCE_REFERENCE_ID, H.VERSION, H.UPDATED_AT
FROM PM_FACTS.HOLDING H;

CREATE OR REPLACE SECURE VIEW PM_SERVING.INSTRUMENTS AS
SELECT I.TENANT_ID, I.INSTRUMENT_ID, I.HOLDING_ID, I.INSTRUMENT_TYPE, I.SECURITY_NAME, I.CURRENCY,
       I.SENIORITY, I.MATURITY_DATE, I.COUPON_RATE, I.SOURCE_REFERENCE_ID, I.VERSION, I.UPDATED_AT
FROM PM_FACTS.INSTRUMENT I;

CREATE OR REPLACE SECURE VIEW PM_SERVING.OBSERVATIONS AS
SELECT O.TENANT_ID,
       O.OBSERVATION_ID,
       O.FUND_ID,
       O.COMPANY_ID,
       C.CANONICAL_NAME AS COMPANY_NAME,
       O.HOLDING_ID,
       O.INSTRUMENT_ID,
       O.METRIC_CODE,
       O.VALUE_NUMBER,
       O.VALUE_STRING,
       O.CURRENCY,
       O.ECONOMIC_PERIOD,
       O.REPORT_DATE,
       O.REVIEW_STATE,
       O.SOURCE_REFERENCE_ID,
       R.DOCUMENT_ID,
       R.PAGE_NUMBER,
       R.SHEET_NAME,
       R.CELL_RANGE,
       O.CONFIDENCE_SCORE,
       O.DELTA_DISPLAY,
       O.RISK_TIER,
       O.VERSION,
       O.UPDATED_AT
FROM PM_FACTS.OBSERVATION O
LEFT JOIN PM_IDENTITY.COMPANY C ON C.GLOBAL_COMPANY_ID = O.COMPANY_ID
LEFT JOIN PM_SOURCE.SOURCE_REFERENCE R
  ON R.TENANT_ID=O.TENANT_ID AND R.SOURCE_REFERENCE_ID=O.SOURCE_REFERENCE_ID
WHERE O.REVIEW_STATE IN ('approved','review_required');

CREATE OR REPLACE SECURE VIEW PM_SERVING.FUND_PERIOD_SNAPSHOTS AS
SELECT S.TENANT_ID,
       S.SNAPSHOT_ID,
       S.FUND_ID,
       F.CANONICAL_NAME AS FUND_NAME,
       S.REPORT_PERIOD,
       S.VERSION,
       S.STATUS,
       ARRAY_SIZE(S.FACT_IDS) AS FACT_COUNT,
       S.BLOCKING_EXCEPTION_COUNT,
       S.SCHEMA_VERSION,
       S.TAXONOMY_VERSION,
       S.CREATED_AT,
       S.PUBLISHED_AT
FROM PM_CONSOLIDATED.FUND_PERIOD_SNAPSHOT S
LEFT JOIN PM_IDENTITY.FUND F ON F.GLOBAL_FUND_ID=S.FUND_ID;

CREATE OR REPLACE SECURE VIEW PM_SERVING.SOURCE_REFERENCES AS
SELECT R.TENANT_ID,
       R.SOURCE_REFERENCE_ID,
       R.DOCUMENT_ID,
       R.DOCUMENT_ARTIFACT_VERSION_ID,
       R.PAGE_NUMBER,
       R.SHEET_NAME,
       R.CELL_RANGE,
       R.BBOX,
       R.EXCERPT,
       A.OBJECT_URI,
       A.STORAGE_VERSION,
       A.QUARANTINE_STATUS
FROM PM_SOURCE.SOURCE_REFERENCE R
JOIN PM_SOURCE.DOCUMENT_ARTIFACT_VERSION A
  ON A.TENANT_ID=R.TENANT_ID AND A.DOCUMENT_ARTIFACT_VERSION_ID=R.DOCUMENT_ARTIFACT_VERSION_ID
WHERE A.QUARANTINE_STATUS='released';
