-- Corvis operational controls v1

ALTER TABLE PM_FACTS.REVIEW_EVENT ADD COLUMN IF NOT EXISTS OUTCOME STRING DEFAULT 'applied';
ALTER TABLE PM_FACTS.REVIEW_EVENT ADD COLUMN IF NOT EXISTS FAILURE_CODE STRING;

ALTER TABLE PM_CONTROL.DELETION_REQUEST ADD COLUMN IF NOT EXISTS EXECUTION_ATTEMPTS NUMBER DEFAULT 0;
ALTER TABLE PM_CONTROL.DELETION_REQUEST ADD COLUMN IF NOT EXISTS LAST_ERROR STRING;

ALTER TABLE PM_SERVING.EXPORT_JOB ADD COLUMN IF NOT EXISTS DELIVERY_ATTEMPTS NUMBER DEFAULT 0;
ALTER TABLE PM_SERVING.EXPORT_JOB ADD COLUMN IF NOT EXISTS LAST_ERROR STRING;

CREATE TABLE IF NOT EXISTS PM_CONTROL.ACCESS_REVIEW (
  TENANT_ID STRING NOT NULL,
  ACCESS_REVIEW_ID STRING NOT NULL,
  REVIEW_PERIOD STRING NOT NULL,
  SUBJECT_COUNT NUMBER NOT NULL,
  PRIVILEGED_SUBJECT_COUNT NUMBER NOT NULL,
  STALE_SUBJECT_COUNT NUMBER NOT NULL,
  FINDINGS VARIANT,
  RESULT STRING NOT NULL,
  GENERATED_AT TIMESTAMP_TZ NOT NULL,
  GENERATED_BY STRING NOT NULL,
  PRIMARY KEY (TENANT_ID, ACCESS_REVIEW_ID)
);
ALTER TABLE PM_CONTROL.ACCESS_REVIEW ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.OPERATIONAL_RUN (
  TENANT_ID STRING NOT NULL,
  OPERATIONAL_RUN_ID STRING NOT NULL,
  RUN_TYPE STRING NOT NULL,
  STATUS STRING NOT NULL,
  STARTED_AT TIMESTAMP_TZ NOT NULL,
  COMPLETED_AT TIMESTAMP_TZ,
  RESULT VARIANT,
  EVIDENCE_URI STRING,
  ACTOR_SUBJECT STRING NOT NULL,
  PRIMARY KEY (TENANT_ID, OPERATIONAL_RUN_ID)
);
ALTER TABLE PM_CONTROL.OPERATIONAL_RUN ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);
