import { correlationId } from "@/lib/server/http";
import { getServerConfig } from "@/lib/server/config";
import { postgres, withTransaction } from "@/lib/server/postgres";
import { authenticateScim, getScimUser, scimErrorResponse, ScimError, setScimUserActive } from "@/lib/server/scim";

export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){try{const db=postgres(getServerConfig().postgresDsn);const config=await authenticateScim(request,db);const {id}=await params;const base=`${new URL(request.url).origin}/api/v1/scim/v2/Users`;const resource=await getScimUser(config,id,base,db);return Response.json({schemas:["urn:ietf:params:scim:schemas:core:2.0:User"],...resource},{headers:{"cache-control":"no-store"}});}catch(error){return scimErrorResponse(error);}}

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){try{const db=postgres(getServerConfig().postgresDsn);const config=await authenticateScim(request,db);const {id}=await params;let body:Record<string,unknown>;try{const value=await request.json();if(!value||typeof value!=="object"||Array.isArray(value))throw new Error();body=value as Record<string,unknown>;}catch{throw new ScimError(400,"invalidSyntax","SCIM patch body required");}const operations=Array.isArray(body.Operations)?body.Operations:[];let active:boolean|undefined;for(const item of operations){if(!item||typeof item!=="object")continue;const op=item as Record<string,unknown>;const path=typeof op.path==="string"?op.path.toLowerCase():"";if(path==="active"&&typeof op.value==="boolean")active=op.value;else if(!path&&op.value&&typeof op.value==="object"&&!Array.isArray(op.value)&&typeof (op.value as Record<string,unknown>).active==="boolean")active=(op.value as Record<string,unknown>).active as boolean;}if(active===undefined)throw new ScimError(400,"invalidValue","Only the active attribute is mutable");await withTransaction(db,(tx)=>setScimUserActive(config,id,active as boolean,correlationId(request),tx));const base=`${new URL(request.url).origin}/api/v1/scim/v2/Users`;const resource=await getScimUser(config,id,base,db);return Response.json({schemas:["urn:ietf:params:scim:schemas:core:2.0:User"],...resource},{headers:{"cache-control":"no-store"}});}catch(error){return scimErrorResponse(error);}}

export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){try{const db=postgres(getServerConfig().postgresDsn);const config=await authenticateScim(request,db);const {id}=await params;await withTransaction(db,(tx)=>setScimUserActive(config,id,false,correlationId(request),tx));return new Response(null,{status:204,headers:{"cache-control":"no-store"}});}catch(error){return scimErrorResponse(error);}}
