"use client";
import { displayDate } from "@/lib/display-format";
import { usePreferences } from "@/features/preferences/preference-provider";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { bulkInviteErrorText, tenantAdminRows } from "@/lib/bulk-invite-csv";
import { throwIfUnauthenticated } from "@/lib/api-errors";
import { downloadText } from "@/lib/download";
import { workspaceContextHeaders } from "@/lib/workspace-context";
import { DataGovernanceSections } from "@/features/access/data-governance-section";
import { SessionPolicySection } from "@/features/access/session-policy-section";

type AuditEvent={auditEventId:string;occurredAt:string;workspaceId?:string;actorSubject:string;action:string;targetType:string;targetId:string;outcome:string;metadata:Record<string,unknown>};
type Grant={supportGrantId:string;workspaceId:string;roleName:string;purpose:string;validFrom:string;validUntil:string;status:"pending_ack"|"active";requiresTenantAck:boolean;subject:string};
type Notice={notificationId:string;kind:string;supportGrantId:string;title:string;message:string;createdAt:string;readAt?:string};
type Invitation={invitationId:string;tenantId:string;workspaceId:string;workspaceName:string;email:string;roleName:string;status:string;createdAt:string;expiresAt:string};
type BulkResult={created:Array<{row:number;name:string;invitation:Invitation;token:string}>;errors:Array<{row:number;error:string}>;summary:{total:number;created:number;failed:number}};

const ROLE_GUIDE=[
  ["Review Analyst","Can review checklists, enter evidence, and draft narratives. Cannot manage users or system settings."],
  ["Program Lead / Workspace Admin","Can oversee all reviews and submit evidence packages. Cannot manage organization-wide users or system settings."],
  ["Organization Admin","Full customer-side access, including user management and review oversight. Reserved for designated customer administrators."],
  ["Corvis Support (break-glass)","Temporary elevated access for authorized Corvis support staff. Always time-limited and fully audited."],
];

function apiUrl(path:string){const base=process.env.NEXT_PUBLIC_CORVIS_API_BASE?.replace(/\/$/,"")??"";return `${base}${path}`;}
async function api<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);for(const [key,value] of Object.entries(workspaceContextHeaders()))headers.set(key,value);const response=await fetch(apiUrl(path),{credentials:"include",cache:"no-store",...init,headers});throwIfUnauthenticated(response);const body=await response.json().catch(()=>({})) as {data?:T;error?:string};if(!response.ok)throw new Error(body.error??`Request failed (${response.status})`);return body.data as T;}
function invitationUrl(invitation:Invitation,token:string){const url=new URL("/invite",window.location.origin);url.searchParams.set("tenantId",invitation.tenantId);url.searchParams.set("workspaceId",invitation.workspaceId);url.hash=token;return url.toString();}

export default function AccessSelfServicePage(){
  usePreferences();
  const [audit,setAudit]=useState<AuditEvent[]>([]);const [grants,setGrants]=useState<Grant[]>([]);const [notices,setNotices]=useState<Notice[]>([]);const [invitations,setInvitations]=useState<Invitation[]>([]);
  const [loading,setLoading]=useState(true);const [loadFailed,setLoadFailed]=useState(false);const [error,setError]=useState("");const [actionReason,setActionReason]=useState("");const [busyId,setBusyId]=useState("");
  const [csv,setCsv]=useState("");const [bulkBusy,setBulkBusy]=useState(false);const [bulkResult,setBulkResult]=useState<BulkResult|null>(null);const [oneTimeLinks,setOneTimeLinks]=useState<Array<{row:number;email:string;url:string}>>([]);
  // Tenant-admin rows grant organization-wide administration; the API refuses them unless the request is explicitly confirmed (#244).
  const [confirmTenantAdmin,setConfirmTenantAdmin]=useState(false);const adminRows=useMemo(()=>tenantAdminRows(csv),[csv]);
  const load=useCallback(async()=>{setLoading(true);setError("");setLoadFailed(false);try{const [nextAudit,support,nextInvites]=await Promise.all([api<AuditEvent[]>("/api/v1/access/audit"),api<{grants:Grant[];notifications:Notice[]}>("/api/v1/access/support"),api<Invitation[]>("/api/v1/access/invitations")]);setAudit(nextAudit);setGrants(support.grants);setNotices(support.notifications);setInvitations(nextInvites);}catch(caught){setLoadFailed(true);setError(caught instanceof Error?caught.message:"Access controls could not be loaded");}finally{setLoading(false);}},[]);
  useEffect(()=>{let active=true;void Promise.all([api<AuditEvent[]>("/api/v1/access/audit"),api<{grants:Grant[];notifications:Notice[]}>("/api/v1/access/support"),api<Invitation[]>("/api/v1/access/invitations")]).then(([nextAudit,support,nextInvites])=>{if(!active)return;setAudit(nextAudit);setGrants(support.grants);setNotices(support.notifications);setInvitations(nextInvites);setError("");}).catch((caught:unknown)=>{if(active){setLoadFailed(true);setError(caught instanceof Error?caught.message:"Access controls could not be loaded");}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  const acknowledge=async(id:string)=>{setBusyId(id);setError("");try{await api("/api/v1/access/support",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"acknowledge",supportGrantId:id})});await load();}catch(caught){setError(caught instanceof Error?caught.message:"Support access could not be acknowledged");}finally{setBusyId("");}};
  const manageInvite=async(invitation:Invitation,action:"resend"|"revoke")=>{if(actionReason.trim().length<3){setError("Enter a reason before resending or revoking an invitation.");return;}setBusyId(invitation.invitationId);setError("");try{const result=await api<{invitation?:Invitation;token?:string}>(`/api/v1/access/invitations/${invitation.invitationId}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,reason:actionReason.trim()})});if(action==="resend"&&result.invitation&&result.token)setOneTimeLinks([{row:0,email:result.invitation.email,url:invitationUrl(result.invitation,result.token)}]);setActionReason("");await load();}catch(caught){setError(caught instanceof Error?caught.message:"Invitation update failed");}finally{setBusyId("");}};
  const uploadCsv=async()=>{if(!csv.trim())return;setBulkBusy(true);setError("");setBulkResult(null);setOneTimeLinks([]);try{const path=adminRows.length&&confirmTenantAdmin?"/api/v1/access/invitations/bulk?confirmTenantAdmin=true":"/api/v1/access/invitations/bulk";const result=await api<BulkResult>(path,{method:"POST",headers:{"content-type":"text/csv; charset=utf-8"},body:csv});setBulkResult(result);setConfirmTenantAdmin(false);setOneTimeLinks(result.created.map((item)=>({row:item.row,email:item.invitation.email,url:invitationUrl(item.invitation,item.token)})));await load();}catch(caught){setError(caught instanceof Error?caught.message:"Bulk import failed");}finally{setBulkBusy(false);}};
  const exportAudit=async()=>{setError("");try{const response=await fetch(apiUrl("/api/v1/access/audit?format=csv"),{credentials:"include",cache:"no-store",headers:workspaceContextHeaders()});throwIfUnauthenticated(response);if(!response.ok)throw new Error("Audit export failed");downloadText("corvis-access-audit.csv",await response.text(),"text/csv;charset=utf-8");}catch(caught){setError(caught instanceof Error?caught.message:"Audit export failed");}};
  const exportBulkErrors=()=>{if(!bulkResult?.errors.length)return;const lines=["row,error",...bulkResult.errors.map((item)=>`${item.row},"${bulkInviteErrorText(item.error).replaceAll('"','""')}"`)];downloadText("corvis-bulk-invite-errors.csv",`${lines.join("\r\n")}\r\n`,"text/csv;charset=utf-8");};
  const pending=invitations.filter((item)=>item.status==="pending");
  // An empty list is only truthful once the load has succeeded.
  const emptyText=(text:string)=>loading?"Loading…":loadFailed?"Unavailable: this data could not be loaded. Use Refresh to try again.":text;
  return <main id="main-content"><div className="app-content">
    <section className="page-heading"><div><p className="eyebrow">Organization access</p><h1>Tenant access controls</h1><p className="lede">Review access changes, onboard users in bulk, manage pending invitations, see every Corvis break-glass support session affecting your organization, check data retention and legal holds, and request a full data export.</p></div><div className="dialog-actions"><Link className="secondary-button" href="/">Back to workspace</Link><button className="secondary-button" disabled={loading} onClick={()=>void load()}>Refresh</button></div></section>
    {error&&<div className="lineage-note tone-danger" role="alert"><strong>Access controls need attention</strong><span>{error}</span></div>}

    <section className="panel" aria-labelledby="support-heading"><div className="panel-heading"><div><p className="eyebrow">Break-glass visibility</p><h2 id="support-heading">Corvis support access</h2></div><span className="table-muted">{grants.filter((g)=>g.status==="active").length} active · {grants.filter((g)=>g.status==="pending_ack").length} awaiting acknowledgement</span></div>
      {notices.filter((n)=>!n.readAt).map((notice)=><div key={notice.notificationId} className="lineage-note tone-warning"><strong>{notice.title}</strong><span>{notice.message}</span></div>)}
      {grants.length?<div className="table-card" tabIndex={0} role="region" aria-label="Support access grants"><table className="data-table"><thead><tr><th>Status</th><th>Support identity</th><th>Role</th><th>Purpose</th><th>Expires</th><th>Action</th></tr></thead><tbody>{grants.map((grant)=><tr key={grant.supportGrantId}><td>{grant.status==="pending_ack"?"Awaiting your acknowledgement":"Active"}</td><td>{grant.subject}</td><td>{grant.roleName}</td><td>{grant.purpose}</td><td>{displayDate(grant.validUntil, { timeStyle: "short" })}</td><td>{grant.status==="pending_ack"?<button className="primary-button button-small" disabled={busyId===grant.supportGrantId} onClick={()=>void acknowledge(grant.supportGrantId)}>Acknowledge & activate</button>:<span className="table-muted">Time-limited</span>}</td></tr>)}</tbody></table></div>:<p className="empty-cell" role={loading?"status":undefined}>{emptyText("No active or pending Corvis support access.")}</p>}
      {notices.some((n)=>!n.readAt)&&<button className="secondary-button" onClick={()=>void api("/api/v1/access/support",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"mark_read"})}).then(()=>load()).catch((caught)=>setError(caught instanceof Error?caught.message:"Notification update failed"))}>Mark notifications read</button>}
    </section>

    <section className="panel" aria-labelledby="bulk-heading"><div className="panel-heading"><div><p className="eyebrow">Enterprise onboarding</p><h2 id="bulk-heading">Bulk invite users by CSV</h2></div></div><p className="lede">Upload up to 500 valid rows. Required columns are <code>email</code>, <code>role</code>, and <code>workspaceId</code>; optional columns are <code>name</code> and <code>reason</code>. Valid rows are invited even when other rows fail.</p>
      <label className="form-field"><span>CSV file</span><input type="file" accept=".csv,text/csv" onChange={(event)=>{const file=event.target.files?.[0];if(file)void file.text().then((text)=>{setCsv(text);setConfirmTenantAdmin(false);setBulkResult(null);}).catch(()=>setError("CSV file could not be read"));}}/></label>
      {csv&&<p className="table-muted">{csv.split(/\r?\n/).filter(Boolean).length-1} data row(s) ready.</p>}{adminRows.length>0&&<div className="lineage-note tone-warning" role="group" aria-labelledby="bulk-admin-heading"><strong id="bulk-admin-heading">{adminRows.length} row(s) grant Organization Admin</strong><span>These addresses will receive full customer-side access, including user management:</span><ul>{adminRows.map((item)=><li key={item.row}>Row {item.row}: {item.email}</li>)}</ul><label className="check-field"><input type="checkbox" checked={confirmTenantAdmin} onChange={(event)=>setConfirmTenantAdmin(event.target.checked)}/><span>I confirm these {adminRows.length} invitation(s) grant organization-wide administration.</span></label></div>}
      <button className="primary-button" disabled={bulkBusy||!csv.trim()||(adminRows.length>0&&!confirmTenantAdmin)} onClick={()=>void uploadCsv()}>{bulkBusy?"Creating invitations…":"Validate & invite"}</button>
      {bulkResult&&<div className={bulkResult.errors.length?"lineage-note tone-warning":"lineage-note tone-success"}><strong>{bulkResult.summary.created} created · {bulkResult.summary.failed} failed</strong><span>Invitation links below are bearer secrets shown only for this response. Send each link only to its named recipient.</span>{bulkResult.errors.length>0&&<button className="secondary-button" onClick={exportBulkErrors}>Download error CSV</button>}</div>}
      {bulkResult&&bulkResult.errors.length>0&&<div className="table-card" tabIndex={0} role="region" aria-label="Rows that were not invited"><table className="data-table"><thead><tr><th>CSV row</th><th>Why it was not invited</th></tr></thead><tbody>{bulkResult.errors.map((item)=><tr key={`${item.row}:${item.error}`}><td>{item.row}</td><td>{bulkInviteErrorText(item.error)}</td></tr>)}</tbody></table></div>}
      {oneTimeLinks.length>0&&<div className="table-card" tabIndex={0} role="region" aria-label="One-time invitation links"><table className="data-table"><thead><tr><th>Recipient</th><th>One-time link</th></tr></thead><tbody>{oneTimeLinks.map((item)=><tr key={`${item.row}:${item.email}`}><td>{item.email}</td><td><input className="input-control" readOnly value={item.url} onFocus={(event)=>event.currentTarget.select()}/></td></tr>)}</tbody></table></div>}
    </section>

    <section className="panel" aria-labelledby="pending-heading"><div className="panel-heading"><div><p className="eyebrow">Invitation lifecycle</p><h2 id="pending-heading">Pending invitations</h2></div><span className="table-muted">{pending.length} pending</span></div><label className="form-field"><span>Reason for resend/revoke</span><input className="input-control" maxLength={1000} value={actionReason} onChange={(event)=>setActionReason(event.target.value)} placeholder="e.g. recipient requested a fresh link"/></label>
      <div className="table-card" tabIndex={0} role="region" aria-label="Pending invitations"><table className="data-table"><thead><tr><th>Recipient</th><th>Workspace</th><th>Role</th><th>Expires</th><th>Actions</th></tr></thead><tbody>{pending.length?pending.map((item)=><tr key={item.invitationId}><td>{item.email}</td><td>{item.workspaceName}</td><td>{item.roleName}</td><td>{displayDate(item.expiresAt, { timeStyle: "short" })}</td><td><div className="dialog-actions"><button className="secondary-button button-small" disabled={busyId===item.invitationId} onClick={()=>void manageInvite(item,"resend")}>Resend</button><button className="secondary-button button-small" disabled={busyId===item.invitationId} onClick={()=>void manageInvite(item,"revoke")}>Revoke</button></div></td></tr>):<tr><td colSpan={5} className="empty-cell">{emptyText("No pending invitations.")}</td></tr>}</tbody></table></div>
    </section>

    <section className="panel" aria-labelledby="roles-heading"><div className="panel-heading"><div><p className="eyebrow">Role guidance</p><h2 id="roles-heading">What each role means</h2></div></div><div className="table-card"><table className="data-table"><thead><tr><th>Role</th><th>Plain-language access</th></tr></thead><tbody>{ROLE_GUIDE.map(([role,description])=><tr key={role}><td><strong>{role}</strong></td><td>{description}</td></tr>)}</tbody></table></div></section>

    <SessionPolicySection/>

    <DataGovernanceSections/>

    <section className="panel" aria-labelledby="audit-heading"><div className="panel-heading"><div><p className="eyebrow">Tenant-scoped evidence</p><h2 id="audit-heading">Access audit trail</h2></div><button className="secondary-button" onClick={()=>void exportAudit()}>Export CSV</button></div><p className="lede">Invitations, member changes, lifecycle actions and support access are shown only for your tenant.</p><div className="table-card" tabIndex={0} role="region" aria-label="Tenant access audit"><table className="data-table"><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Target</th><th>Outcome</th></tr></thead><tbody>{audit.length?audit.map((event)=><tr key={event.auditEventId}><td>{displayDate(event.occurredAt, { timeStyle: "short" })}</td><td>{event.actorSubject}</td><td>{event.action}</td><td>{event.targetType} · {event.targetId}</td><td>{event.outcome}</td></tr>):<tr><td colSpan={5} className="empty-cell">{emptyText("No tenant access events recorded.")}</td></tr>}</tbody></table></div></section>
  </div></main>;
}
