-- Template: provision a tenant-isolated Snowflake role.
-- Replace <TENANT_ROLE> with CORVIS_TENANT_<first 16 uppercase hex chars of SHA-256(tenant_id)>
-- and <TENANT_ID> with the exact canonical tenant identifier.

CREATE ROLE IF NOT EXISTS <TENANT_ROLE>;
GRANT USAGE ON DATABASE CORVIS TO ROLE <TENANT_ROLE>;
GRANT USAGE ON SCHEMA CORVIS.PM_SOURCE TO ROLE <TENANT_ROLE>;
GRANT USAGE ON SCHEMA CORVIS.PM_CANONICAL TO ROLE <TENANT_ROLE>;
GRANT USAGE ON SCHEMA CORVIS.PM_CURATED TO ROLE <TENANT_ROLE>;
GRANT USAGE ON SCHEMA CORVIS.PM_SERVING TO ROLE <TENANT_ROLE>;
GRANT USAGE ON SCHEMA CORVIS.PM_CONTROL TO ROLE <TENANT_ROLE>;

GRANT SELECT, INSERT, UPDATE ON TABLE CORVIS.PM_SOURCE.DOCUMENT TO ROLE <TENANT_ROLE>;
GRANT SELECT, INSERT, UPDATE ON TABLE CORVIS.PM_SOURCE.DOCUMENT_UPLOAD TO ROLE <TENANT_ROLE>;
GRANT SELECT, INSERT, UPDATE ON TABLE CORVIS.PM_SOURCE.DOCUMENT_ARTIFACT_VERSION TO ROLE <TENANT_ROLE>;
GRANT SELECT ON TABLE CORVIS.PM_SOURCE.SOURCE_REFERENCE TO ROLE <TENANT_ROLE>;
GRANT SELECT ON TABLE CORVIS.PM_SOURCE.DOCUMENT_CHUNK TO ROLE <TENANT_ROLE>;
GRANT SELECT, UPDATE ON TABLE CORVIS.PM_CANONICAL.OBSERVATION TO ROLE <TENANT_ROLE>;
GRANT SELECT, UPDATE ON TABLE CORVIS.PM_CURATED.FUND_PERIOD_SNAPSHOT TO ROLE <TENANT_ROLE>;
GRANT SELECT, INSERT ON TABLE CORVIS.PM_CONTROL.REVIEW_EVENT TO ROLE <TENANT_ROLE>;
GRANT SELECT, INSERT, UPDATE ON TABLE CORVIS.PM_CONTROL.ENTITLEMENT TO ROLE <TENANT_ROLE>;
GRANT SELECT ON ALL VIEWS IN SCHEMA CORVIS.PM_SERVING TO ROLE <TENANT_ROLE>;

MERGE INTO CORVIS.PM_CONTROL.ROLE_TENANT_ACCESS TARGET
USING (SELECT '<TENANT_ROLE>' AS ROLE_NAME, '<TENANT_ID>' AS TENANT_ID) SOURCE
ON TARGET.ROLE_NAME = SOURCE.ROLE_NAME AND TARGET.TENANT_ID = SOURCE.TENANT_ID
WHEN MATCHED THEN UPDATE SET ACTIVE = TRUE
WHEN NOT MATCHED THEN INSERT (ROLE_NAME, TENANT_ID, ACTIVE) VALUES (SOURCE.ROLE_NAME, SOURCE.TENANT_ID, TRUE);

-- The service principal must be allowed to assume this role. The exact grant target
-- depends on whether the application authenticates to Snowflake as a USER or SERVICE.
-- Example for a service user:
-- GRANT ROLE <TENANT_ROLE> TO USER CORVIS_APP_SERVICE;
