"use client";
import { useEffect, useEffectEvent, useRef, useState } from "react";
import { Modal } from "@/shared/ui/modal";
import { type SavedScreen, type ViewConfiguration, VIEW_COLUMNS } from "@/modules/workspace/domain/saved-views";
import { usePreferences } from "./preference-provider";
export function SavedViews({ screen, configuration, onApply, onColumns, skipDefault = false }: { screen: SavedScreen; configuration: ViewConfiguration; onApply: (v: ViewConfiguration) => void; onColumns: (columns: string[]) => void; skipDefault?: boolean }) {
  const preferences = usePreferences(); const [selected, setSelected] = useState(""); const [dialog, setDialog] = useState<"save" | "rename" | "delete" | null>(null); const [name, setName] = useState(""); const [shared, setShared] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const initial = useRef(false);
  const views = preferences.views.filter((v) => v.screen === screen); const chosen = views.find((v) => v.id === selected); const columns = configuration.columns as string[] ?? VIEW_COLUMNS[screen];
  const applyDefault = useEffectEvent((id: string, configuration: ViewConfiguration) => { setSelected(id); onApply(configuration); });
  useEffect(() => {
    if (!preferences.ready || initial.current) return;
    if (skipDefault) { initial.current = true; return; }
    const saved = preferences.views.find((v) => v.screen === screen && v.id === preferences.defaults[screen]);
    if (saved) { let active = true; queueMicrotask(() => { if (active) { initial.current = true; applyDefault(saved.id, saved.configuration); } }); return () => { active = false; }; }
    initial.current = true;
  }, [preferences.ready, preferences.views, preferences.defaults, screen, skipDefault]);
  const mutate = async (command: Record<string, unknown>) => { setBusy(true); setError(""); try { await preferences.mutateView({ ...command, screen }); setDialog(null); if (command.action === "delete") setSelected(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not update this view"); } finally { setBusy(false); } };
  return <section className="saved-views" aria-label="Saved views"><div className="toolbar"><label className="form-field">Saved view<select aria-label="Saved view" value={selected} onChange={(e) => { const id = e.target.value; setSelected(id); const view = views.find((v) => v.id === id); if (view) onApply(view.configuration); }}><option value="">Current view</option>{views.map((v) => <option key={v.id} value={v.id}>{v.name}{v.shared ? " · shared" : ""}{preferences.defaults[screen] === v.id ? " · default" : ""}</option>)}</select></label>
    <button className="secondary-button button-small" disabled={!preferences.ready || !!preferences.error || busy} onClick={() => { setName(""); setShared(false); setDialog("save"); }}>Save view</button>
    {chosen && <><button className="text-button" disabled={busy} onClick={() => void mutate({ action: "default", id: preferences.defaults[screen] === selected ? null : selected })}>{preferences.defaults[screen] === selected ? "Clear default" : "Make default"}</button>{chosen.owned ? <><button className="text-button" disabled={busy} onClick={() => { setName(chosen.name); setDialog("rename"); }}>Rename view</button><button className="text-button" disabled={busy} onClick={() => void mutate({ action: "share", id: selected, shared: !chosen.shared })}>{chosen.shared ? "Stop sharing" : "Share with workspace"}</button><button className="text-button" disabled={busy} onClick={() => setDialog("delete")}>Delete view</button></> : <span>Shared view · read-only</span>}</>}
    <details><summary>Columns</summary><fieldset className="column-options"><legend>Visible columns</legend>{VIEW_COLUMNS[screen].map((column) => <label key={column}><input type="checkbox" checked={columns.includes(column)} disabled={columns.length === 1 && columns.includes(column)} onChange={(e) => onColumns(e.target.checked ? [...columns, column] : columns.filter((v) => v !== column))}/>{column}</label>)}</fieldset></details>
  </div>{(error || preferences.error) && <p role="alert">{error || preferences.error}</p>}{dialog && <Modal label={dialog === "save" ? "Save view" : dialog === "rename" ? "Rename view" : "Delete view"} onClose={() => setDialog(null)}><form className="dialog-body" onSubmit={(e) => { e.preventDefault(); void mutate(dialog === "save" ? { action: "create", name, configuration, shared } : dialog === "rename" ? { action: "rename", id: selected, name } : { action: "delete", id: selected }); }}><h2>{dialog === "save" ? "Save view" : dialog === "rename" ? "Rename view" : "Delete view"}</h2>{dialog !== "delete" ? <label className="form-field">View name<input autoFocus value={name} maxLength={80} required onChange={(e) => setName(e.target.value)}/></label> : <p>Delete “{chosen?.name}”? Workspace members will no longer see this shared view.</p>}{dialog === "save" && <label><input type="checkbox" checked={shared} onChange={(e) => setShared(e.target.checked)}/>Share read-only with this workspace</label>}<p>Views save filters and layout. Every person sees only data they can currently access.</p>{error && <p role="alert">{error}</p>}<div className="dialog-actions"><button type="button" className="secondary-button" onClick={() => setDialog(null)}>Cancel</button><button className="primary-button" disabled={busy}>{dialog === "delete" ? "Delete view" : "Save"}</button></div></form></Modal>}</section>;
}
