-- Corvis enterprise platform baseline
-- Apply with the CORVIS_PLATFORM_SERVICE role in a dedicated database.

CREATE SCHEMA IF NOT EXISTS PM_CONTROL;
CREATE SCHEMA IF NOT EXISTS PM_SOURCE;
CREATE SCHEMA IF NOT EXISTS PM_CANONICAL;
CREATE SCHEMA IF NOT EXISTS PM_CURATED;
CREATE SCHEMA IF NOT EXISTS PM_SEMANTIC;
CREATE SCHEMA IF NOT EXISTS PM_SERVING;

CREATE TABLE IF NOT EXISTS PM_CONTROL.ROLE_TENANT_ACCESS (
  ROLE_NAME STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ROLE_NAME, TENANT_ID)
);

CREATE OR REPLACE ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION AS (ROW_TENANT_ID STRING)
RETURNS BOOLEAN ->
  CURRENT_ROLE() = 'CORVIS_PLATFORM_SERVICE'
  OR EXISTS (
    SELECT 1
    FROM PM_CONTROL.ROLE_TENANT_ACCESS ACCESS_MAP
    WHERE ACCESS_MAP.ROLE_NAME = CURRENT_ROLE()
      AND ACCESS_MAP.TENANT_ID = ROW_TENANT_ID
      AND ACCESS_MAP.ACTIVE = TRUE
  );

CREATE TABLE IF NOT EXISTS PM_SOURCE.DOCUMENT (
  DOCUMENT_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  LOGICAL_STATUS STRING NOT NULL,
  FUND_ID STRING,
  FUND_NAME STRING,
  REPORT_PERIOD STRING,
  DOCUMENT_TYPE STRING DEFAULT 'Source document',
  PAGE_COUNT NUMBER DEFAULT 0,
  QUALITY STRING DEFAULT 'Pending',
  OBSERVATION_COUNT NUMBER DEFAULT 0,
  PROGRESS_PERCENT NUMBER DEFAULT 0,
  CREATED_BY STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  DELETED_AT TIMESTAMP_TZ,
  PRIMARY KEY (DOCUMENT_ID)
);
ALTER TABLE PM_SOURCE.DOCUMENT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_SOURCE.DOCUMENT_UPLOAD (
  UPLOAD_ID STRING NOT NULL,
  DOCUMENT_ID STRING NOT NULL,
  ARTIFACT_VERSION_ID STRING NOT NULL,
  INGESTION_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  OBJECT_KEY STRING NOT NULL,
  FINAL_OBJECT_KEY STRING NOT NULL,
  S3_UPLOAD_ID STRING NOT NULL,
  FILE_NAME STRING NOT NULL,
  CONTENT_TYPE STRING NOT NULL,
  SIZE_BYTES NUMBER NOT NULL,
  LAST_MODIFIED NUMBER,
  PART_SIZE NUMBER NOT NULL,
  STATUS STRING NOT NULL,
  IDEMPOTENCY_KEY STRING NOT NULL,
  SHA256 STRING,
  SCAN_RESULT VARIANT,
  CREATED_BY STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (UPLOAD_ID),
  UNIQUE (TENANT_ID, IDEMPOTENCY_KEY)
);
ALTER TABLE PM_SOURCE.DOCUMENT_UPLOAD ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_SOURCE.DOCUMENT_ARTIFACT_VERSION (
  ARTIFACT_VERSION_ID STRING NOT NULL,
  DOCUMENT_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  OBJECT_KEY STRING NOT NULL,
  FILE_NAME STRING NOT NULL,
  CONTENT_TYPE STRING NOT NULL,
  SIZE_BYTES NUMBER NOT NULL,
  SHA256 STRING NOT NULL,
  DUPLICATE_OF_ARTIFACT_VERSION_ID STRING,
  SCAN_STATUS STRING NOT NULL,
  CREATED_BY STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  DELETED_AT TIMESTAMP_TZ,
  PRIMARY KEY (ARTIFACT_VERSION_ID)
);
ALTER TABLE PM_SOURCE.DOCUMENT_ARTIFACT_VERSION ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_SOURCE.SOURCE_REFERENCE (
  SOURCE_REFERENCE_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  DOCUMENT_ID STRING NOT NULL,
  ARTIFACT_VERSION_ID STRING NOT NULL,
  PAGE_NUMBER NUMBER,
  PAGE_LABEL STRING,
  BOUNDING_BOX VARIANT,
  EXCERPT STRING,
  SOURCE_DOCUMENT_ACCESS_ALLOWED BOOLEAN NOT NULL DEFAULT FALSE,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (SOURCE_REFERENCE_ID)
);
ALTER TABLE PM_SOURCE.SOURCE_REFERENCE ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_SOURCE.DOCUMENT_CHUNK (
  CHUNK_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  DOCUMENT_ID STRING NOT NULL,
  ARTIFACT_VERSION_ID STRING NOT NULL,
  SOURCE_REFERENCE_ID STRING NOT NULL,
  FUND_ID STRING,
  PAGE_NUMBER NUMBER,
  TEXT STRING NOT NULL,
  SOURCE_DOCUMENT_ACCESS_ALLOWED BOOLEAN NOT NULL DEFAULT FALSE,
  CHUNK_INDEX NUMBER,
  REPRESENTATION_VERSION STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (CHUNK_ID)
);
ALTER TABLE PM_SOURCE.DOCUMENT_CHUNK ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CANONICAL.OBSERVATION (
  OBSERVATION_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  FUND_ID STRING,
  FUND_NAME STRING,
  COMPANY_ID STRING,
  COMPANY_NAME STRING,
  HOLDING_ID STRING,
  INSTRUMENT_ID STRING,
  METRIC_CODE STRING NOT NULL,
  METRIC_LABEL STRING,
  NUMERIC_VALUE NUMBER(38, 12),
  DISPLAY_VALUE STRING,
  CORRECTED_DISPLAY_VALUE STRING,
  PERIOD_LABEL STRING,
  PERIOD_END DATE,
  DELTA_DISPLAY STRING,
  CONFIDENCE_PERCENT NUMBER,
  REVIEW_STATE STRING NOT NULL DEFAULT 'Needs review',
  MATERIALITY STRING NOT NULL DEFAULT 'normal',
  SOURCE_REFERENCE_ID STRING,
  FUND_PERIOD_SNAPSHOT_ID STRING,
  REVIEWED_BY STRING,
  REVIEWED_AT TIMESTAMP_TZ,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (OBSERVATION_ID)
);
ALTER TABLE PM_CANONICAL.OBSERVATION ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CURATED.FUND_PERIOD_SNAPSHOT (
  FUND_PERIOD_SNAPSHOT_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  FUND_ID STRING NOT NULL,
  FUND_NAME STRING,
  REPORT_PERIOD STRING NOT NULL,
  VERSION NUMBER NOT NULL,
  STATUS STRING NOT NULL DEFAULT 'Review',
  HOLDINGS_COUNT NUMBER DEFAULT 0,
  FACTS_COUNT NUMBER DEFAULT 0,
  MANIFEST VARIANT,
  PUBLISHED_BY STRING,
  PUBLISHED_AT TIMESTAMP_TZ,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (FUND_PERIOD_SNAPSHOT_ID)
);
ALTER TABLE PM_CURATED.FUND_PERIOD_SNAPSHOT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.AUDIT_EVENT (
  AUDIT_EVENT_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  ACTOR_SUBJECT STRING NOT NULL,
  ACTOR_EMAIL STRING,
  ROLES VARIANT,
  ACTION STRING NOT NULL,
  RESOURCE_TYPE STRING NOT NULL,
  RESOURCE_ID STRING,
  OUTCOME STRING NOT NULL,
  REQUEST_ID STRING,
  METADATA VARIANT,
  OCCURRED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (AUDIT_EVENT_ID)
);
ALTER TABLE PM_CONTROL.AUDIT_EVENT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.REVIEW_EVENT (
  REVIEW_EVENT_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  OBSERVATION_ID STRING NOT NULL,
  REVIEWER_SUBJECT STRING NOT NULL,
  DECISION STRING NOT NULL,
  PREVIOUS_VALUE STRING,
  CORRECTED_VALUE STRING,
  REASON STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (REVIEW_EVENT_ID)
);
ALTER TABLE PM_CONTROL.REVIEW_EVENT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.JOB (
  JOB_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  JOB_TYPE STRING NOT NULL,
  IDEMPOTENCY_KEY STRING NOT NULL,
  PAYLOAD VARIANT NOT NULL,
  STATUS STRING NOT NULL,
  ATTEMPT_COUNT NUMBER NOT NULL DEFAULT 0,
  AVAILABLE_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  LEASED_BY STRING,
  LEASED_UNTIL TIMESTAMP_TZ,
  LAST_ERROR STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  COMPLETED_AT TIMESTAMP_TZ,
  PRIMARY KEY (JOB_ID),
  UNIQUE (TENANT_ID, JOB_TYPE, IDEMPOTENCY_KEY)
);
ALTER TABLE PM_CONTROL.JOB ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.EXPORT_EVENT (
  EXPORT_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  SNAPSHOT_ID STRING NOT NULL,
  FORMAT STRING NOT NULL,
  OBJECT_KEY STRING NOT NULL,
  SHA256 STRING NOT NULL,
  MANIFEST VARIANT NOT NULL,
  CREATED_BY STRING NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  EXPIRES_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (EXPORT_ID)
);
ALTER TABLE PM_CONTROL.EXPORT_EVENT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.ENTITLEMENT (
  ENTITLEMENT_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  SUBJECT STRING NOT NULL,
  RESOURCE_TYPE STRING NOT NULL,
  RESOURCE_ID STRING NOT NULL,
  PERMISSION STRING NOT NULL,
  ALLOWED BOOLEAN NOT NULL DEFAULT TRUE,
  EFFECTIVE_FROM TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  EFFECTIVE_TO TIMESTAMP_TZ,
  CREATED_BY STRING,
  UPDATED_BY STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ENTITLEMENT_ID)
);
ALTER TABLE PM_CONTROL.ENTITLEMENT ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.USER_DIRECTORY (
  USER_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  EXTERNAL_ID STRING,
  USER_NAME STRING,
  DISPLAY_NAME STRING,
  EMAIL STRING,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  ROLES VARIANT,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (USER_ID)
);
ALTER TABLE PM_CONTROL.USER_DIRECTORY ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE OR REPLACE SECURE VIEW PM_SERVING.DOCUMENTS_V AS
SELECT
  D.TENANT_ID,
  D.DOCUMENT_ID,
  U.FILE_NAME,
  D.FUND_NAME,
  D.REPORT_PERIOD,
  D.DOCUMENT_TYPE,
  D.PAGE_COUNT,
  U.SIZE_BYTES,
  CASE
    WHEN U.SIZE_BYTES >= 1073741824 THEN TO_VARCHAR(ROUND(U.SIZE_BYTES / 1073741824, 1)) || ' GB'
    WHEN U.SIZE_BYTES >= 1048576 THEN TO_VARCHAR(ROUND(U.SIZE_BYTES / 1048576, 1)) || ' MB'
    ELSE TO_VARCHAR(ROUND(U.SIZE_BYTES / 1024, 1)) || ' KB'
  END AS SIZE_DISPLAY,
  CASE D.LOGICAL_STATUS
    WHEN 'PUBLISHED' THEN 'Published'
    WHEN 'REVIEW' THEN 'Review'
    WHEN 'EXTRACTING' THEN 'Extracting'
    WHEN 'QUEUED' THEN 'Queued'
    ELSE INITCAP(LOWER(D.LOGICAL_STATUS))
  END AS STATUS,
  D.PROGRESS_PERCENT,
  TO_VARCHAR(U.CREATED_AT, 'YYYY-MM-DD HH24:MI') AS UPLOADED_DISPLAY,
  U.CREATED_AT AS UPLOADED_AT,
  D.QUALITY,
  D.OBSERVATION_COUNT
FROM PM_SOURCE.DOCUMENT D
JOIN PM_SOURCE.DOCUMENT_UPLOAD U ON U.DOCUMENT_ID = D.DOCUMENT_ID AND U.TENANT_ID = D.TENANT_ID
QUALIFY ROW_NUMBER() OVER (PARTITION BY D.TENANT_ID, D.DOCUMENT_ID ORDER BY U.CREATED_AT DESC) = 1;

CREATE OR REPLACE SECURE VIEW PM_SERVING.OBSERVATIONS_V AS
SELECT
  O.TENANT_ID,
  O.OBSERVATION_ID,
  O.FUND_ID,
  O.FUND_NAME,
  O.COMPANY_ID,
  O.COMPANY_NAME,
  O.METRIC_CODE,
  O.METRIC_LABEL,
  O.NUMERIC_VALUE,
  COALESCE(O.CORRECTED_DISPLAY_VALUE, O.DISPLAY_VALUE) AS DISPLAY_VALUE,
  O.PERIOD_LABEL,
  O.PERIOD_END,
  O.DELTA_DISPLAY,
  O.CONFIDENCE_PERCENT,
  O.REVIEW_STATE,
  O.MATERIALITY,
  O.SOURCE_REFERENCE_ID,
  O.FUND_PERIOD_SNAPSHOT_ID,
  COALESCE(O.COMPANY_NAME, O.FUND_NAME, 'Source') || ' · ' || COALESCE(O.PERIOD_LABEL, '') AS SOURCE_LABEL
FROM PM_CANONICAL.OBSERVATION O;

CREATE OR REPLACE SECURE VIEW PM_SERVING.METRIC_FACTS_V AS
SELECT * FROM PM_SERVING.OBSERVATIONS_V WHERE REVIEW_STATE <> 'Rejected';

CREATE OR REPLACE SECURE VIEW PM_SERVING.FUND_PERIOD_SNAPSHOTS_V AS
SELECT TENANT_ID, FUND_PERIOD_SNAPSHOT_ID, FUND_ID, FUND_NAME, REPORT_PERIOD, VERSION, STATUS,
       HOLDINGS_COUNT, FACTS_COUNT, CREATED_AT, UPDATED_AT, PUBLISHED_AT
FROM PM_CURATED.FUND_PERIOD_SNAPSHOT;

CREATE OR REPLACE SECURE VIEW PM_SERVING.SOURCE_REFERENCES_V AS
SELECT R.TENANT_ID, R.SOURCE_REFERENCE_ID, R.DOCUMENT_ID, R.ARTIFACT_VERSION_ID, A.OBJECT_KEY,
       R.PAGE_NUMBER, R.PAGE_LABEL, R.BOUNDING_BOX, R.EXCERPT, R.SOURCE_DOCUMENT_ACCESS_ALLOWED
FROM PM_SOURCE.SOURCE_REFERENCE R
JOIN PM_SOURCE.DOCUMENT_ARTIFACT_VERSION A
  ON A.TENANT_ID = R.TENANT_ID AND A.ARTIFACT_VERSION_ID = R.ARTIFACT_VERSION_ID
WHERE A.DELETED_AT IS NULL;

CREATE OR REPLACE SECURE VIEW PM_SERVING.RECENT_ACTIVITY_V AS
SELECT TENANT_ID, ACTION, RESOURCE_TYPE, RESOURCE_ID, OUTCOME, OCCURRED_AT
FROM PM_CONTROL.AUDIT_EVENT;

-- Service role owns migrations and worker/admin operations.
CREATE ROLE IF NOT EXISTS CORVIS_PLATFORM_SERVICE;
GRANT USAGE ON DATABASE CORVIS TO ROLE CORVIS_PLATFORM_SERVICE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CORVIS TO ROLE CORVIS_PLATFORM_SERVICE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE CORVIS TO ROLE CORVIS_PLATFORM_SERVICE;
GRANT SELECT ON ALL VIEWS IN DATABASE CORVIS TO ROLE CORVIS_PLATFORM_SERVICE;
GRANT SELECT ON PM_CONTROL.ROLE_TENANT_ACCESS TO ROLE CORVIS_PLATFORM_SERVICE;
