-- Production document retrieval index.
-- Run after 001_enterprise_platform.sql and after CORVIS_SERVING_WH exists.
-- The indexed attributes are required for permission filtering before retrieval.

CREATE CORTEX SEARCH SERVICE IF NOT EXISTS PM_SEMANTIC.DOCUMENT_SEARCH
  ON TEXT
  PRIMARY KEY (CHUNK_ID)
  ATTRIBUTES TENANT_ID, DOCUMENT_ID, ARTIFACT_VERSION_ID, SOURCE_REFERENCE_ID, FUND_ID, PAGE_NUMBER, SOURCE_DOCUMENT_ACCESS_ALLOWED
  WAREHOUSE = CORVIS_SERVING_WH
  TARGET_LAG = '5 minutes'
  REQUEST_LOGGING = TRUE
  AUTO_SUSPEND = 300
AS
SELECT
  CHUNK_ID,
  TENANT_ID,
  DOCUMENT_ID,
  ARTIFACT_VERSION_ID,
  SOURCE_REFERENCE_ID,
  FUND_ID,
  PAGE_NUMBER,
  SOURCE_DOCUMENT_ACCESS_ALLOWED,
  TEXT
FROM PM_SOURCE.DOCUMENT_CHUNK
WHERE SOURCE_DOCUMENT_ACCESS_ALLOWED = TRUE;
