-- Enterprise operational controls layered on the baseline schema.

ALTER TABLE PM_CONTROL.JOB ADD COLUMN IF NOT EXISTS LEASE_TOKEN STRING;

CREATE TABLE IF NOT EXISTS PM_CONTROL.FEATURE_FLAG (
  TENANT_ID STRING NOT NULL,
  FLAG_KEY STRING NOT NULL,
  ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
  EMERGENCY_DISABLED BOOLEAN NOT NULL DEFAULT FALSE,
  CONFIG VARIANT,
  UPDATED_BY STRING,
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (TENANT_ID, FLAG_KEY)
);
ALTER TABLE PM_CONTROL.FEATURE_FLAG ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.WEBHOOK_SUBSCRIPTION (
  SUBSCRIPTION_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  TARGET_URL STRING NOT NULL,
  EVENT_TYPES ARRAY NOT NULL,
  ENCRYPTED_SECRET STRING NOT NULL,
  ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_BY STRING,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (SUBSCRIPTION_ID)
);
ALTER TABLE PM_CONTROL.WEBHOOK_SUBSCRIPTION ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.WEBHOOK_DELIVERY (
  DELIVERY_ID STRING NOT NULL,
  TENANT_ID STRING NOT NULL,
  SUBSCRIPTION_ID STRING NOT NULL,
  EVENT_TYPE STRING NOT NULL,
  IDEMPOTENCY_KEY STRING NOT NULL,
  PAYLOAD VARIANT NOT NULL,
  STATUS STRING NOT NULL DEFAULT 'QUEUED',
  ATTEMPT_COUNT NUMBER NOT NULL DEFAULT 0,
  AVAILABLE_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  LAST_HTTP_STATUS NUMBER,
  LAST_ERROR STRING,
  DELIVERED_AT TIMESTAMP_TZ,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (DELIVERY_ID),
  UNIQUE (TENANT_ID, SUBSCRIPTION_ID, IDEMPOTENCY_KEY)
);
ALTER TABLE PM_CONTROL.WEBHOOK_DELIVERY ADD ROW ACCESS POLICY PM_CONTROL.TENANT_ISOLATION ON (TENANT_ID);

CREATE TABLE IF NOT EXISTS PM_CONTROL.CONTROL_EVIDENCE (
  EVIDENCE_ID STRING NOT NULL,
  TENANT_ID STRING,
  CONTROL_CODE STRING NOT NULL,
  EVIDENCE_TYPE STRING NOT NULL,
  STATUS STRING NOT NULL,
  SUMMARY STRING,
  DETAILS VARIANT,
  SOURCE_SYSTEM STRING,
  OCCURRED_AT TIMESTAMP_TZ NOT NULL,
  RECORDED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (EVIDENCE_ID)
);

CREATE OR REPLACE SECURE VIEW PM_SERVING.FEATURE_FLAGS_V AS
SELECT TENANT_ID, FLAG_KEY, IFF(EMERGENCY_DISABLED, FALSE, ENABLED) AS ENABLED, CONFIG, UPDATED_AT
FROM PM_CONTROL.FEATURE_FLAG;
