import type { ActivityRecord, FundSnapshot, View } from "@/core/contracts";
import { Icon } from "@/components/ui/icon";
import { StatusPill } from "@/components/ui/status-pill";

export function OverviewView({ snapshots, activity, onNavigate, onUpload }: { snapshots: FundSnapshot[]; activity: ActivityRecord[]; onNavigate: (view: View) => void; onUpload: () => void }) {
  return <>
    <section className="hero-row"><div><p className="eyebrow">THURSDAY · 18 SEPTEMBER</p><h1>Good morning, Alex.</h1><p className="lede">Your Q2 reporting cycle is 78% complete. Two funds need attention.</p></div><button className="primary-button" onClick={onUpload}><Icon name="upload" />Upload documents</button></section>
    <section className="metric-grid">
      <button className="metric-card" onClick={() => onNavigate("documents")}><div className="metric-head"><span>Documents this quarter</span><span className="metric-icon"><Icon name="file" /></span></div><strong>42</strong><p><b>+8</b> since last week</p></button>
      <button className="metric-card" onClick={() => onNavigate("review")}><div className="metric-head"><span>Trusted observations</span><span className="metric-icon"><Icon name="database" /></span></div><strong>6,284</strong><p><b>97.8%</b> auto-approved</p></button>
      <button className="metric-card warning" onClick={() => onNavigate("review")}><div className="metric-head"><span>Needs review</span><span className="metric-icon"><Icon name="alert" /></span></div><strong>14</strong><p>Across <b>2 funds</b></p></button>
      <div className="metric-card"><div className="metric-head"><span>Published snapshots</span><span className="metric-icon"><Icon name="check" /></span></div><strong>18</strong><p><b>4</b> published this week</p></div>
    </section>
    <section className="two-column"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">FUND PERIODS</p><h2>Current reporting cycle</h2></div><button className="text-button" onClick={() => onNavigate("documents")}>View all <Icon name="arrow" size={15}/></button></div><div className="snapshot-list">{snapshots.map((item) => <div className="snapshot-row" key={item.fund}><div className="fund-mark">{item.fund.split(" ").slice(0,2).map((word) => word[0]).join("")}</div><div className="snapshot-main"><strong>{item.fund}</strong><span>{item.period} · {item.holdings} holdings · {item.facts} facts</span></div><StatusPill status={item.status}/><span className="muted-time">{item.changed}</span><Icon name="chevron" size={16}/></div>)}</div></div><div className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">ACTIVITY</p><h2>What changed</h2></div></div><div className="activity-list">{activity.map((item, i) => <div className="activity-row" key={item.title}><span className={`activity-marker marker-${i}`}></span><div><strong>{item.title}</strong><span>{item.detail}</span></div><time>{item.time}</time></div>)}</div></div></section>
    <section className="research-callout" onClick={() => onNavigate("research")} role="button" tabIndex={0}><div className="research-symbol"><Icon name="spark" size={22}/></div><div><p className="eyebrow">ASK CORVIS</p><h3>What changed in my portfolio this quarter?</h3><p>Query trusted fund data and source documents together, with evidence.</p></div><div className="research-arrow"><Icon name="arrow"/></div></section>
  </>;
}
